name: Notify Email

description: Send email via Gmail using EMAIL_CONFIG secret

inputs:
  status:
    description: Build status (success or failure)
    required: true
  environment:
    description: Environment name (e.g., dev, prod)
    required: true
  email_config:
    description: JSON string containing email configuration
    required: true

runs:
  using: composite
  steps:
    - name: Parse EMAIL_CONFIG input
      shell: bash
      run: |
        echo '${{ inputs.email_config }}' > email_config.json
        echo "EMAIL_USERNAME=$(jq -r .username email_config.json)" >> $GITHUB_ENV
        echo "EMAIL_PASSWORD=$(jq -r .password email_config.json)" >> $GITHUB_ENV
        echo "EMAIL_TO=$(jq -r .to email_config.json)" >> $GITHUB_ENV

    - name: Send Email
      uses: dawidd6/action-send-mail@v3
      env:
        USERNAME: ${{ env.EMAIL_USERNAME }}
        PASSWORD: ${{ env.EMAIL_PASSWORD }}
        TO: ${{ env.EMAIL_TO }}
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ env.USERNAME }}
        password: ${{ env.PASSWORD }}
        to: ${{ env.TO }}
        from: ${{ env.USERNAME }}
        subject: ${{ inputs.status == 'success' && format('✅ Build Successful - {0}', github.repository) || format('❌ Build Failed - {0}', github.repository) }}
        body: |
          Build ${{ inputs.status }} for ${{ github.repository }}.
          Environment: ${{ inputs.environment }}
          Commit: ${{ github.sha }}
          Actor: ${{ github.actor }}
          Workflow: ${{ github.workflow }}
          Run: ${{ github.run_id }}
          Logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}