name: Send Email Notification
description: Sends email summary based on result

inputs:
  status:
    required: true
  environment:
    required: true
  summary:
    required: true

runs:
  using: composite
  steps:
    - name: Parse EMAIL_CONFIG input
      shell: bash
      run: |
        echo '${{ inputs.email_config }}' > email_config.json
        echo "EMAIL_USERNAME=$(jq -r .username email_config.json)" >> $GITHUB_ENV
        echo "EMAIL_PASSWORD=$(jq -r .password email_config.json)" >> $GITHUB_ENV
        echo "EMAIL_TO=$(jq -r .to email_config.json)" >> $GITHUB_ENV

    - name: Send Email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ env.EMAIL_USERNAME }}
        password: ${{ env.EMAIL_PASSWORD }}
        to: ${{ env.EMAIL_TO }}
        from: ${{ env.EMAIL_USERNAME }}
        subject: "[${{ inputs.environment }}] Build ${{ inputs.status == 'success' && '✅ SUCCESS' || '❌ FAILURE' }} - ${{ github.repository }}"
        content_type: html
        body: |
          <h3>CI/CD Build Report</h3>
          <p><strong>Status:</strong> ${{ inputs.status }}</p>
          <p><strong>Environment:</strong> ${{ inputs.environment }}</p>
          <p><strong>Commit:</strong> <code>${{ github.sha }}</code></p>
          <p><strong>Actor:</strong> ${{ github.actor }}</p>
          <p><strong>Workflow:</strong> ${{ github.workflow }}</p>
          <p><strong>Run:</strong> <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">View on GitHub</a></p>
          <hr />
          <h4>Test Summary</h4>
          <table border="1" cellspacing="0" cellpadding="6" style="border-collapse:collapse;font-family:monospace;">
            <tr><th>Class</th><th>Tests</th><th>Failures</th><th>Errors</th><th>Skipped</th><th>Time</th></tr>
            ${{ inputs.log_summary }}
          </table>