apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: backend
type: Opaque
data:
  username: cG9zdGdyZXM=  # Base64 encoded 'postgres'
  password: c2VjdXJlcGFzc3dvcmQ=  # Base64 encoded 'securepassword'
