name: Parse Maven Logs
description: Extract test result summary from Maven logs

inputs:
  build_status:
    description: Maven build exit code
    required: true

outputs:
  log_summary:
    description: Test results in HTML table rows
    value: ${{ steps.extract.outputs.summary }}

runs:
  using: "composite"
  steps:
    - name: Parse logs and extract summary
      id: extract
      shell: bash
      run: |
        summary=""
        while IFS= read -r line; do
          if [[ "$line" =~ Tests\ run:\ ([0-9]+),\ Failures:\ ([0-9]+),\ Errors:\ ([0-9]+),\ Skipped:\ ([0-9]+),\ Time\ elapsed:\ ([0-9.]+)\ s\ --\ in\ (.*) ]]; then
            tests="${BASH_REMATCH[1]}"
            failures="${BASH_REMATCH[2]}"
            errors="${BASH_REMATCH[3]}"
            skipped="${BASH_REMATCH[4]}"
            time="${BASH_REMATCH[5]}"
            class="${BASH_REMATCH[6]}"
            summary+="<tr><td>$class</td><td>$tests</td><td>$failures</td><td>$errors</td><td>$skipped</td><td>${time}s</td></tr>\n"
          fi
        done < logs/maven.log

        if [[ -z "$summary" ]]; then
          summary="<tr><td colspan='6'>No test results found</td></tr>"
        fi

        echo "summary<<EOF" >> $GITHUB_OUTPUT
        echo -e "$summary" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT