name: Parse Maven Logs
description: Parses Maven logs and generates test summary
inputs:
  build_status:
    required: true
    description: Build exit code
outputs:
  log_summary:
    description: Test summary in HTML format
runs:
  using: composite
  steps:
    - name: Extract test results
      shell: bash
      run: |
        set -euo pipefail
        summary=""
        logfile="logs/maven.log"

        if [[ ! -f "$logfile" ]]; then
          echo "log_summary=<tr><td colspan='6'>Log file not found</td></tr>" >> $GITHUB_OUTPUT
          exit 0
        fi

        while IFS= read -r line; do
          if [[ "$line" =~ Tests\ run:\ ([0-9]+),\ Failures:\ ([0-9]+),\ Errors:\ ([0-9]+),\ Skipped:\ ([0-9]+),\ Time\ elapsed:\ ([0-9.]+)\ s\ --\ in\ (.*) ]]; then
            tests="${BASH_REMATCH[1]}"
            failures="${BASH_REMATCH[2]}"
            errors="${BASH_REMATCH[3]}"
            skipped="${BASH_REMATCH[4]}"
            time="${BASH_REMATCH[5]}"
            class="${BASH_REMATCH[6]}"
            summary+="<tr><td>$class</td><td>$tests</td><td>$failures</td><td>$errors</td><td>$skipped</td><td>${time}s</td></tr>\n"
          fi
        done < "$logfile"

        if [[ -z "$summary" ]]; then
          summary="<tr><td colspan='6'>No test results found</td></tr>"
        fi

        echo -e "log_summary<<EOF\n$summary\nEOF" >> $GITHUB_OUTPUT