name: Parse Maven Logs
description: Extract test result summary from Maven logs

inputs:
  build_status:
    description: Maven build exit code
    required: true

outputs:
  log_summary:
    description: Test results in HTML table rows
    value: ${{ steps.extract.outputs.log_summary }}

runs:
  using: "composite"
  steps:
    - name: Parse Maven Log (HTML Table)
      id: format
      shell: bash
      run: |
        echo "<html><body>" > email.html

        if [[ "${{ inputs.build_status }}" == "0" ]]; then
          echo "<h2 style='color:green;'>Build Success</h2>" >> email.html
        else
          echo "<h2 style='color:red;'>Build Failed</h2>" >> email.html
        fi

        echo "<h3>Test Summary:</h3><table border='1'><tr><th>Summary</th></tr>" >> email.html
        grep -E "Tests run:" maven.log | sed 's/^/<tr><td>/' | sed 's/$/<\/td><\/tr>/' >> email.html
        echo "</table>" >> email.html

        echo "<h3>Failures & Errors:</h3><table border='1'><tr><th>Error</th></tr>" >> email.html
        grep -A 3 -E "<<< FAILURE!|<<< ERROR!" maven.log | sed 's/^/<tr><td>/' | sed 's/$/<\/td><\/tr>/' >> email.html
        echo "</table>" >> email.html

        echo "</body></html>" >> email.html

        echo "log_summary<<EOF" >> $GITHUB_OUTPUT
        cat email.html >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT