- name: Parse Maven logs
  shell: bash
  run: |
    set -euo pipefail
    log_file="logs/maven.log"

    # If log is missing or empty, skip parsing but still set a default output
    if [[ ! -s "$log_file" ]]; then
      echo "No Maven test log found or file is empty; skipping parse."
      echo "log_summary=No test results." >> "$GITHUB_OUTPUT"
      exit 0
    fi

    # Example parse logic (avoid grep failing the script):
    # Use '|| true' so grep returning 1 doesn’t abort when set -e is on
    failures=$(grep -Eo "Failures: [1-9]" "$log_file" || true)
    if [[ -n "$failures" ]]; then
      color="red"
      text="$failures failures"
    else
      color="green"
      text="All tests passed"
    fi

    # Emit HTML-formatted rows as output (use $GITHUB_OUTPUT to set composite outputs)
    echo "log_summary<<EOF" >> "$GITHUB_OUTPUT"
    echo "<tr><td><font color=\"$color\">$text</font></td></tr>" >> "$GITHUB_OUTPUT"
    echo "EOF" >> "$GITHUB_OUTPUT"