name: Parse Maven Logs
description: Extract test result summary from Maven logs

inputs:
  build_status:
    description: Maven build exit code
    required: true

outputs:
  log_summary:
    description: Test results in HTML table rows
    value: ${{ steps.extract.outputs.summary }}

runs:
  using: "composite"
  steps:
    - name: Parse logs and extract summary
      id: extract
      shell: bash
      run: |
        summary=""
        if [ "${{ inputs.build_status }}" -eq 0 ]; then
          grep -A5 "Results :" maven.log > parsed.log || echo "No test summary found."
        else
          grep -E 'COMPILATION ERROR|BUILD FAILURE|Tests run:|^\[ERROR\]' maven.log > parsed.log || echo "No known failure patterns found."
        fi

        echo "log_summary<<EOF" >> $GITHUB_OUTPUT
        cat parsed.log >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT