replicaCount: 2

image:
  repository: kubevamshi/vamika-backend
  tag: "v1.0.0-0218150735"
  pullPolicy: Always

  
database:
  host: postgres.backend.svc.cluster.local
  port: 5432
  name: backenddb
  userSecret: postgres-secret
  
resources:
  requests:
    memory: 100Mi
    cpu: 100m
  limits:
    cpu: 150m
    memory: 150Mi
securityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 999
createNamespace: true
