name: Maven Build and Test
description: Builds and tests a Maven project and saves logs.

runs:
  using: "composite"
  steps:
    - name: Build with Maven
      id: build
      shell: bash
      run: |
        mkdir -p logs
        set -o pipefail
        mvn clean test | tee logs/maven.log
        echo "status=$?" >> $GITHUB_OUTPUT