name: Automation Deployment -Prod

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
           
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Unit Tests with Coverage
        run: mvn clean test jacoco:report

      - name: Build Spring Boot App
        run: mvn -B package -DskipTests

      - name: surefire-reports
        run: |
          ls -lR target/surefire-reports
      
      - name: jacoco-reports
        run: |
          ls -lR target/site/jacoco/
      
      - name: Upload Test Reports
        uses: actions/upload-artifact@main
        with:
          name: test-reports
          path: |
            target/surefire-reports/*.xml
            target/site/jacoco/*.html
          if-no-files-found: warn
      
      - name: Notify on success
        if: success()
        uses: ./.github/actions/notify-email
        with:
          status: success
          environment: prod
          email_config: ${{ vars.EMAIL_CONFIG }}

      - name: Notify on failure
        if: failure()
        uses: ./.github/actions/notify-email
        with:
          status: failure
          environment: prod
          email_config: ${{ vars.EMAIL_CONFIG }}
