name: Automation testing-QA

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
           
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Unit Tests
        run: mvn -B test

      - name: Run Integration Tests & Verify
        run: mvn -B verify

      - name: Generate JaCoCo Coverage Report
        run: mvn jacoco:report

      - name: Build Spring Boot App
        run: mvn -B package -DskipTests
