name: Automation testing-QA

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test Network Connectivity
        run: curl -I https://github.com

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Test SMTP Connectivity
        run: |
          openssl s_client -starttls smtp -connect smtp.gmail.com:587

      - name: Run Unit Tests with Coverage
        run: mvn clean test jacoco:report

      - name: Build Spring Boot App
        run: mvn -B package -DskipTests

      - name: surefire-reports
        run: |
          ls -lR target/surefire-reports
          chmod 777 target/surefire-reports/*.xml
      - name: jacoco-reports
        run: |
          ls -lR target/site/jacoco/

      # - name: Manually Download Upload Artifact Action
      #   run: |
      #     git clone https://github.com/actions/upload-artifact.git
      #     cd upload-artifact
      #     git checkout v3.1.2

      # - name: Upload JUnit Test Reports
      #   uses: ./upload-artifact
      #   with:
      #     name: backend_junit_reports
      #     path: target/surefire-reports/

      - name: Send Test Reports via Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: "smtp.gmail.com"
          server_port: "587"
          username: "vamika6522@gmail.com"
          password: "arjvepxvfdrctuei"
          subject: "Test Reports - Build #${{ github.run_number }}"
          to: "chvamshikrishna24@gmail.com"
          from: "vamika6522@gmail.com"
          body: "Please find the attached test reports."
          attachments: |
            target/surefire-reports/*.xml
            target/site/jacoco/*.html
