name: Automation testing-QA

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
           
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Tests (unit + Integration)
        run: mvn test
        
      - name: Generate Test Report
        run: |
          mkdir -p test-reports
          cp target/surefire-reports/*.xml test-reports/

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: test-reports/
