name: Automation testing-QA

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Unit Tests with Coverage
        run: mvn clean test jacoco:report

      - name: Build Spring Boot App
        run: mvn -B package -DskipTests

      # - name: Upload JUnit Test Reports
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: backend-junit-reports
      #     path: target/surefire-reports/

      # - name: Upload JaCoCo Coverage Report
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: backend-jacoco-report
      #     path: target/site/jacoco/
