name: Automation testing-dev

on:
  #push:
  #  branches:
  #    - dev
  #pull_request:
  #  branches:
  #    - dev

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Run Unit Tests with Coverage
        run: mvn clean test jacoco:report

      - name: Build Spring Boot App
        run: mvn -B package -DskipTests

      - name: surefire-reports
        run: |
          ls -lR target/surefire-reports
      
      - name: jacoco-reports
        run: |
          ls -lR target/site/jacoco/
      
      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            target/surefire-reports/*.xml
            target/site/jacoco/*.html
          if-no-files-found: warn
      - name: Generate success summary
        if: success()
        run: echo "Build completed successfully at $(date)" > summary.txt
        
      - name: Generate failure summary
        if: failure()
        run: |
          echo "Build failed. Recent logs:" > summary.txt
          tail -n 50 target/surefire-reports/*.txt >> summary.txt || echo "No logs found" >> summary.txt
      - name: Read log summary
        id: read_summary
        run: |
          SUMMARY=$(cat summary.txt)
          SUMMARY_ESCAPED="${SUMMARY//'%'/'%25'}"
          SUMMARY_ESCAPED="${SUMMARY_ESCAPED//$'\n'/'%0A'}"
          SUMMARY_ESCAPED="${SUMMARY_ESCAPED//$'\r'/'%0D'}"
          echo "summary=$SUMMARY_ESCAPED" >> $GITHUB_OUTPUT

      - name: Notify on success
        if: success()
        uses: ./.github/actions/notify-email
        with:
          status: success
          environment: dev
          email_config: ${{ vars.EMAIL_CONFIG }}

      - name: Notify on failure
        if: failure()
        uses: ./.github/actions/notify-email
        with:
          status: failure
          environment: dev
          email_config: ${{ vars.EMAIL_CONFIG }}
    


      # - name: Send Test Reports via Email
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     server_address: "smtp.gmail.com"
      #     server_port: "587"
      #     username: "vamika6522@gmail.com"
      #     password: "arjvepxvfdrctuei"
      #     subject: "Test Reports - Build #${{ github.run_number }}"
      #     to: "chvamshikrishna24@gmail.com"
      #     from: "vamika6522@gmail.com"
      #     body: "Please find the attached test reports."
      #     attachments: |
      #       target/surefire-reports/*.xml
      #       target/site/jacoco/*.html
