name: UAT Actions Build and Test

on:
  # push:
  #   branches:
  #     - feature/test
  #     - uat
  #     - develop-GitHubActions
  # pull_request:
  #   types: [opened, reopened, synchronize]
  workflow_dispatch:
    inputs:
      test_names_list:
        type: string
        description: "List of test names to run"
        required: true
        default: ""
      only_first_execution:
        type: boolean
        description: "Run only the first execution"
        default: false
      upload_to_zephyr:
        type: boolean
        description: "Upload results to Zephyr"
        default: true
      zephyr_cycle:
        type: string
        description: "Zephyr cycle name"
        required: true
        default: "Github_Actions_Cycle"
      overwrite_params:
        type: string
        description: "Overwrite execution parameters"
        default: "{\n\t\n}"
      batch_time:
        type: string
        description: "Batch time for scheduling"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      API_CONSUMER_KEY: ${{ secrets.DEV_CONSUMER_KEY }}
      API_PRIVATE_KEY: ${{ secrets.DEV_PRIVATE_KEY }}
      SONAR_HOST_URL: 'https://sonarqubeenterprise.pgcloud.com/sonarqube'
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      TEST_NAMES_LIST: ${{ inputs.test_names_list }}
      ONLY_FIRST_EXECUTION: ${{ inputs.only_first_execution }}
      UPLOAD_TO_ZEPHYR: ${{ inputs.upload_to_zephyr }}
      ZEPHYR_CYCLE: ${{ inputs.zephyr_cycle }}
      OVERWRITE_PARAMS: ${{ inputs.overwrite_params }}
      BATCH_TIME: ${{ inputs.batch_time }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'
        cache: maven

    - name: Debug Environment Variables
      run: env

    - name: Install dependencies
      run: mvn clean install

    - name: Run Tests
      run: |
        chmod +x src/test/resources/chromedriver
          mvn test \
            -Dtest="${{ inputs.test_names_list }}" \
            -Dexecution.headless=true \
            -Ddebug.attachDriverSession=false \
            -Ddebug.onlyFirstExecution=${{ env.ONLY_FIRST_EXECUTION }} \
            -Djira.connection.enabled=${{ env.UPLOAD_TO_ZEPHYR }} \
            -Djira.cycle.name="${{ env.ZEPHYR_CYCLE }}" \
            -DfailIfNoTests=false \
            -Dexecution.params.overwrite="${{ env.OVERWRITE_PARAMS }}"

