name: Vamika-backend

on: 
    workflow_dispatch:

jobs:
    build-image_tag_update:
        runs-on: ubuntu-latest
        env:
            IMAGE_NAME: "vamika-backend:v0.0.1"
            BUILDER_IMAGE: "maven:3.9.9-ibm-semeru-17-focal"
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Docker Login
              run: |
                echo "${{ secrets.IMAGE_REGISTRY_TOKEN }}" | docker login -u ${{ secrets.IMAGE_REGISTRY_USERNAME }} --password-stdin
            - name: Docker Build
              run: |
                COMMIT_AUTHOR=$(git log -1 --pretty=%an)
                COMMIT_ID=$(git rev-parse --short "$GITHUB_SHA")
                docker buildx build \
                  --build-arg BUILDER_IMAGE="${{ env.BUILDER_IMAGE }}" \
                  --label "AUTHOR=${COMMIT_AUTHOR}" \
                  --label "COMMIT_ID=${COMMIT_ID}" \
                  -t "${{ secrets.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}" \
                  .
            - name: Push Docker image
              run: |
                docker push ${{ secrets.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
            - name: Docker Logout
              run: |
                docker logout ${{ secrets.IMAGE_REGISTRY }}
            
            - name: Update Flux CD Git repository
              run: |
                git config --global user.email "chvamshikrishna24@gmail.com"
                git config --global user.namen "vamshi"
                git clone https://github.com/vamika-store/vamika-backend.git
                cd vamika-backend
                ls -R
                sed -i 's|tag: .*| tag: "${{ github.sha }}"|' ./chart/vm-microservice/values.yaml
                git commit -am "Update backend image tag to ${{ github.sha }}"
                git push

